apiVersion: apps/v1
kind: Deployment
metadata:
  name: drink
  namespace: drink
  labels:
    name: drink
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drink
  template:
    metadata:
      labels:
        app: drink
    spec:
      containers:
        - name: drink
          image: d3spina/t-web-800:drink-latest
          imagePullPolicy: Always
          env:
            - name: ROCKET_ADDRESS
              value: "0.0.0.0"
            - name: ROCKET_PORT
              value: "8003"
          ports:
            - containerPort: 8002
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: my-docker-credentials