apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: sleep
  labels:
    name: sleep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: d3spina/t-web-800:sleep-latest
          imagePullPolicy: Always
          env:
            - name: ROCKET_ADDRESS
              value: "0.0.0.0"
            - name: ROCKET_PORT
              value: "8004"
          ports:
            - containerPort: 8004
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: my-docker-credentials