version: '3.8'
services:
        mon-service:
                build:
                        context: .
                        dockerfile: Dockerfile
                image: travel
                ports:
                        - "8005:8005"
                environment:
                        ROCKET_ADDRESS: "0.0.0.0"
                        ROCKET_PORT: "8005"