version: '3.8'
services:
        mon-service:
                build:
                        context: .
                        dockerfile: Dockerfile
                image: drink
                ports:
                        - "8000:8000"