apiVersion: v1
kind: Service
metadata:
  name: drink-service
  namespace: drink
spec:
  selector:
    app: drink
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003
  type: LoadBalancer
