apiVersion: v1
kind: Service
metadata:
  name: travel-service
  namespace: travel
spec:
  selector:
    app: travel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8006
  type: LoadBalancer
