apiVersion: v1
kind: Service
metadata:
  name: sleep-service
  namespace: sleep
spec:
  selector:
    app: sleep
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8004
  type: LoadBalancer
