[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#common = { path = "../common" }
tokio = {  version = "1.36.0", features = ["full"] }
anyhow = "1.0.80"
reqwest = "0.11.25"
serde_json = "1.0.114"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
<<<<<<< Updated upstream
warp = "0.3.6"
=======
serde = { version = "1.0.197", features = ["derive"] }
>>>>>>> Stashed changes
