name: Rust-test

on:
  push:
    branches: 
     - service-eat
     - service-auth
     - service-drink
     - service-sleep
     - service-enjoy
     - service-travel
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Clean cache
        run: cargo clean
      - name: Run tests
        run: cargo test
