name: Rust

on:
  push:
    branches: 
     - main
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Change to service directory
      run: cd services/eat/src
    - name: Normes
      run: cargo fmt
    - name: Run tests
      run: |
        cd common/src
        cargo test --verbose
