name: Rust-eat

on:
  push:
    branches: 
     - service-eat
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Normes
      run: cargo fmt
    - name: Run tests
      run: |
        cd services/eat/src
        cargo test --verbose
    - name: Build
      run: |
        cd services/eat/src
        cargo build --verbose
