name: Deploy Service Eat

on:
  workflow_run:
    workflows: ["Rust-eat"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag d3spina/t-web-800:eat-latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: docker push d3spina/t-web-800:eat-latest

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl rollout status deployment/eat -n eat
